services:
  app:
    build: .
    container_name: server-health-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-controller
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  mongo:
    image: mongo:6
    container_name: server-health-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  jenkins_home:
